const Images = {
  splashBackground: require('../../assets/images/logo.png'),
  examinationPackage: require('../../assets/images/health_book_icon.png'),
  avatar: require('../../assets/icons/ic_account.png'),
  avatarCamera: require('../../assets/icons/ic_account1.png'),
  bill: require('../../assets/images/bill.png'),
  calendar: require('../../assets/images/calendar.png'),
  advisory: require('../../assets/images/advisory.png'),
  contact: require('../../assets/images/contact.png'),
  changeAvt: require('../../assets/images/change-avt.png'),
  search: require('../../assets/images/search-fast.png'),
  BacSi: require('../../assets/images/bacsi.png'),
  CauHoi: require('../../assets/images/cauhoi.png'),
  ArrowRight: require('../../assets/images/arrowRight.png'),
  User: require('../../assets/images/user.png'),
  UserOrange: require('../../assets/images/doctor.png'),

  billIcon: [
    require('../../assets/images/ic_1.png'),
    require('../../assets/images/ic_2.png'),
    require('../../assets/images/ic_3.png'),
    require('../../assets/images/ic_4.png'),
    require('../../assets/images/ic_5.png'),
    require('../../assets/images/ic_6.png'),
  ],
  categoriesIcon: [
    require('../../assets/images/noisoitieuhoa.png'),
    require('../../assets/images/taimuihong.png'),
    require('../../assets/images/chuandoanhinhanh.png'),
    require('../../assets/images/first-aid-kit.png'),
    require('../../assets/images/khoamat.png'),
    require('../../assets/images/nhakhoa.png'),
    require('../../assets/images/health_book_icon.png'),
    require('../../assets/images/child-disease.png'),
    require('../../assets/images/xetnghiem.png'),
    require('../../assets/images/noitongquat.png'),
    require('../../assets/images/sanphukhoa.png'),
  ],
  goiKhamIcon: [
    require('../../assets/images/general-gynecology.png'),
    require('../../assets/images/heart_ailment.png'),
    require('../../assets/images/liver-cancer.png'),
    require('../../assets/images/diabetes-mellitus.png'),
    require('../../assets/images/diabetes.png'),
    require('../../assets/images/marriage_icon.png'),
    require('../../assets/images/child-disease.png'),
    require('../../assets/images/cancer_icon.png'),
    require('../../assets/images/overview_icon.png'),
    require('../../assets/images/gynaecology-obstetrics.png'),
  ],
  bgMap: require('../../assets/images/bg-map.jpg'),
  doctor: require('../../assets/images/doctor.png'),
  question: require('../../assets/images/question.png'),
};

export default Images;
